import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
  buildRecordingDriveRetentionManifest,
  buildGeneratedRecordingTranscriptText,
  createRecordingDriveHandoffFiles,
  buildDaVinciResolveXml,
  buildFinalCutProXml,
  buildPremiereProXml,
  createPodcastAudioBundle,
  createRecordingBundle,
  type RecordingMarker,
} from '../src/components/RecordingPanel.tsx';

const source = {
  roomName: 'Launch <Demo> & Review',
  sessionId: 'session-1',
  createdAt: '2026-06-11T10:00:00.000Z',
  durationSeconds: 65,
  files: [],
};

const bundleFiles = [
  {
    label: 'Host Camera',
    fileName: 'host.webm',
    zipPath: 'tracks/01_host.webm',
    size: 128,
    type: 'video/webm',
    kind: 'video' as const,
  },
  {
    label: 'Host Mic',
    fileName: 'host-audio.webm',
    zipPath: 'tracks/02_host-audio.webm',
    size: 64,
    type: 'audio/webm',
    kind: 'audio' as const,
  },
];

const audioStemFiles = [
  {
    label: 'Host Mic WAV stem',
    format: 'wav' as const,
    zipPath: 'audio-stems/02_host-audio.wav',
    size: 1024,
    type: 'audio/wav',
    sourceTrackIndex: 2,
    sourceZipPath: 'tracks/02_host-audio.webm',
    sampleRate: 48000,
    channels: 1,
    bitDepth: 16 as const,
    encoding: 'pcm_s16le' as const,
  },
];

const markers: RecordingMarker[] = [
  {
    id: 'marker-1',
    label: 'Clip this "answer"',
    seconds: 12.5,
    createdAt: '2026-06-11T10:00:12.500Z',
  },
];

describe('recording bundle editor export', () => {
  it('builds a Final Cut Pro XML project starter with tracks, stems, and markers', () => {
    const xml = buildFinalCutProXml(source, bundleFiles, audioStemFiles, markers);

    assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>/);
    assert.match(xml, /<fcpxml version="1\.10">/);
    assert.match(xml, /Launch &lt;Demo&gt; &amp; Review/);
    assert.match(xml, /src="\.\.\/tracks\/01_host\.webm"/);
    assert.match(xml, /src="\.\.\/audio-stems\/02_host-audio\.wav"/);
    assert.match(xml, /audioRole="dialogue"/);
    assert.match(xml, /value="Clip this &quot;answer&quot;"/);
  });

  it('includes the FCPXML sidecar and manifest entry in recording bundles', async () => {
    const bundle = await createRecordingBundle({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
      ],
      markers,
    } as any);
    const text = new TextDecoder().decode(await bundle.arrayBuffer());

    assert.match(text, /editor\/local_recording_timeline\.fcpxml/);
    assert.match(text, /Final Cut Pro XML/);
    assert.match(text, /<fcpxml version="1\.10">/);
  });

  it('builds an Adobe Premiere Pro XML sequence starter with tracks, stems, and markers', () => {
    const xml = buildPremiereProXml(source, bundleFiles, audioStemFiles, markers);

    assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>/);
    assert.match(xml, /<xmeml version="5">/);
    assert.match(xml, /Launch &lt;Demo&gt; &amp; Review/);
    assert.match(xml, /<pathurl>\.\.\/tracks\/01_host\.webm<\/pathurl>/);
    assert.match(xml, /<pathurl>\.\.\/audio-stems\/02_host-audio\.wav<\/pathurl>/);
    assert.match(xml, /<name>Clip this &quot;answer&quot;<\/name>/);
    assert.match(xml, /<timebase>30<\/timebase>/);
  });

  it('includes the Premiere XML sidecar and manifest entry in recording bundles', async () => {
    const bundle = await createRecordingBundle({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
      ],
      markers,
    } as any);
    const text = new TextDecoder().decode(await bundle.arrayBuffer());

    assert.match(text, /editor\/premiere_pro_sequence\.xml/);
    assert.match(text, /Adobe Premiere Pro XML/);
    assert.match(text, /<xmeml version="5">/);
  });

  it('builds a DaVinci Resolve XML timeline starter with tracks, stems, and markers', () => {
    const xml = buildDaVinciResolveXml(source, bundleFiles, audioStemFiles, markers);

    assert.match(xml, /^<\?xml version="1\.0" encoding="UTF-8"\?>/);
    assert.match(xml, /DaVinci Resolve timeline XML generated by LiveStream Studio/);
    assert.match(xml, /Launch &lt;Demo&gt; &amp; Review - DaVinci Resolve/);
    assert.match(xml, /<pathurl>\.\.\/tracks\/01_host\.webm<\/pathurl>/);
    assert.match(xml, /<pathurl>\.\.\/audio-stems\/02_host-audio\.wav<\/pathurl>/);
    assert.match(xml, /<name>Clip this &quot;answer&quot;<\/name>/);
    assert.match(xml, /<timebase>30<\/timebase>/);
  });

  it('includes the DaVinci Resolve XML sidecar and manifest entry in recording bundles', async () => {
    const bundle = await createRecordingBundle({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
      ],
      markers,
    } as any);
    const text = new TextDecoder().decode(await bundle.arrayBuffer());

    assert.match(text, /editor\/davinci_resolve_timeline\.xml/);
    assert.match(text, /DaVinci Resolve XML/);
    assert.match(text, /DaVinci Resolve timeline XML generated by LiveStream Studio/);
  });

  it('preserves participant ISO tracks as video-class editor assets', async () => {
    const bundle = await createRecordingBundle({
      ...source,
      files: [
        {
          label: 'Host ISO',
          fileName: 'host-iso.webm',
          blob: new Blob(['iso-track'], { type: 'video/webm' }),
          kind: 'iso',
        },
      ],
    } as any);
    const text = new TextDecoder().decode(await bundle.arrayBuffer());

    assert.match(text, /"label": "Host ISO"/);
    assert.match(text, /"kind": "iso"/);
    assert.match(text, /Host ISO,0:00,0,1:05,65,tracks\/01_host-iso\.webm/);
    assert.match(text, /<asset id="asset1" name="Host ISO"/);
  });

  it('creates podcast audio bundles without video tracks', async () => {
    const bundle = await createPodcastAudioBundle({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
        {
          label: 'Host Mic',
          fileName: 'host-audio.webm',
          blob: new Blob(['audio-track'], { type: 'audio/webm' }),
          kind: 'audio',
        },
      ],
      captionLanguage: 'en-US',
      captionSegments: [
        {
          id: 'caption-1',
          speakerName: 'Host',
          text: 'Welcome to the show.',
          interim: false,
          timestamp: '2026-06-11T10:00:05.000Z',
        },
      ],
      markers,
    } as any);
    const text = new TextDecoder().decode(await bundle.arrayBuffer());

    assert.match(text, /podcast-audio-bundle/);
    assert.match(text, /audio-tracks\/01_host-audio\.webm/);
    assert.match(text, /LiveStream Studio Podcast Audio Export/);
    assert.match(text, /captions\/live_captions\.txt/);
    assert.match(text, /markers\/recording_markers\.csv/);
    assert.doesNotMatch(text, /tracks\/01_host\.webm/);
    assert.doesNotMatch(text, /video-track/);
  });

  it('adds generated transcripts to recording and podcast bundles', async () => {
    const generatedTranscript = {
      text: 'Welcome to the generated transcript.',
      model: 'whisper-1',
      createdAt: '2026-06-11T10:02:00.000Z',
      sourceFileName: 'host-audio.webm',
      sourceLabel: 'Host Mic',
      language: 'en',
      durationSeconds: 10,
    };
    const bundleSource = {
      ...source,
      files: [
        {
          label: 'Host Mic',
          fileName: 'host-audio.webm',
          blob: new Blob(['audio-track'], { type: 'audio/webm' }),
          kind: 'audio',
        },
      ],
      generatedTranscript,
    };

    const textExport = buildGeneratedRecordingTranscriptText(bundleSource as any, generatedTranscript);
    assert.match(textExport, /LiveStream Studio Generated Transcript/);
    assert.match(textExport, /Welcome to the generated transcript/);

    const recordingBundle = await createRecordingBundle(bundleSource as any);
    const recordingText = new TextDecoder().decode(await recordingBundle.arrayBuffer());
    assert.match(recordingText, /captions\/generated_transcript\.txt/);
    assert.match(recordingText, /Generated transcript/);
    assert.match(recordingText, /"generatedTranscript"/);

    const podcastBundle = await createPodcastAudioBundle(bundleSource as any);
    const podcastText = new TextDecoder().decode(await podcastBundle.arrayBuffer());
    assert.match(podcastText, /captions\/generated_transcript\.txt/);
    assert.match(podcastText, /Welcome to the generated transcript/);
  });

  it('builds Google Drive handoff files with raw tracks and production bundles', async () => {
    const handoffFiles = await createRecordingDriveHandoffFiles({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
        {
          label: 'Host Mic',
          fileName: 'host-audio.webm',
          blob: new Blob(['audio-track'], { type: 'audio/webm' }),
          kind: 'audio',
        },
      ],
      markers,
    } as any);

    assert.deepEqual(
      handoffFiles.map((file) => file.label),
      ['Host Camera', 'Host Mic', 'Editor bundle ZIP', 'Podcast audio ZIP']
    );
    assert.match(handoffFiles[2].fileName, /Launch__Demo__&_Review_recording_bundle_2026-06-11-10-00-00\.zip/);
    assert.match(handoffFiles[3].fileName, /Launch__Demo__&_Review_podcast_audio_2026-06-11-10-00-00\.zip/);

    const editorBundleText = new TextDecoder().decode(await handoffFiles[2].blob.arrayBuffer());
    assert.match(editorBundleText, /manifest\.json/);
    assert.match(editorBundleText, /editor\/local_recording_timeline\.csv/);
    assert.match(editorBundleText, /markers\/recording_markers\.csv/);

    const podcastBundleText = new TextDecoder().decode(await handoffFiles[3].blob.arrayBuffer());
    assert.match(podcastBundleText, /podcast-audio-bundle/);
    assert.match(podcastBundleText, /audio-tracks\/01_host-audio\.webm/);
  });

  it('adds a portable Google Drive retention manifest to handoff files', async () => {
    const retention = {
      policyId: 'cloud-30-days' as const,
      label: '30-day cloud handoff',
      uploadedAt: '2026-06-11T10:05:00.000Z',
      expiresAt: '2026-07-11T10:05:00.000Z',
      permanent: false,
    };
    const manifest = buildRecordingDriveRetentionManifest(source, retention);
    const handoffFiles = await createRecordingDriveHandoffFiles({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
      ],
    } as any, retention);

    assert.match(manifest, /google-drive-retention-policy/);
    assert.match(manifest, /2026-07-11T10:05:00\.000Z/);
    assert.deepEqual(
      handoffFiles.map((file) => file.label),
      ['Host Camera', 'Editor bundle ZIP', 'Drive retention manifest']
    );
    assert.match(handoffFiles[2].fileName, /Launch__Demo__&_Review_drive_retention_2026-06-11-10-00-00\.json/);
    assert.match(
      new TextDecoder().decode(await handoffFiles[2].blob.arrayBuffer()),
      /Review or remove this Drive handoff after 2026-07-11T10:05:00\.000Z/
    );
  });

  it('omits the podcast handoff ZIP when no audio track exists', async () => {
    const handoffFiles = await createRecordingDriveHandoffFiles({
      ...source,
      files: [
        {
          label: 'Host Camera',
          fileName: 'host.webm',
          blob: new Blob(['video-track'], { type: 'video/webm' }),
          kind: 'video',
        },
      ],
    } as any);

    assert.deepEqual(
      handoffFiles.map((file) => file.label),
      ['Host Camera', 'Editor bundle ZIP']
    );
  });

  it('rejects podcast audio bundles when no audio tracks exist', async () => {
    await assert.rejects(
      createPodcastAudioBundle({
        ...source,
        files: [
          {
            label: 'Host Camera',
            fileName: 'host.webm',
            blob: new Blob(['video-track'], { type: 'video/webm' }),
            kind: 'video',
          },
        ],
      } as any),
      /at least one audio track/
    );
  });
});
