apiVersion: v1
kind: Service
metadata:
  name: livestream-studio-server
  labels:
    app.kubernetes.io/name: livestream-studio-server
    app.kubernetes.io/component: signaling
    app.kubernetes.io/part-of: livestream-studio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: livestream-studio-server
    app.kubernetes.io/component: signaling
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: livestream-studio-media-server
  labels:
    app.kubernetes.io/name: livestream-studio-media-server
    app.kubernetes.io/component: media-relay
    app.kubernetes.io/part-of: livestream-studio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: livestream-studio-media-server
    app.kubernetes.io/component: media-relay
  ports:
    - name: http
      port: 80
      targetPort: http
